### ISSUE TITLE
question on animation code

### ISSUE THREAD

**Issue by trenkert** [beefoo/memory-underground#1]
sorry, I am new to D3.js. 

I really love the animation of the subway map, and I would love to use it for an own open source project. 

For this project, I wouldn't need it to calculate how to render things like "shared memories as transfer stations", I would just need to declare the name, line, position and kind of stop in an json file and have d3.js create the animation accordingly. 

This means I don't need 80% of the application, just the visualization part. 

My problem now is that I am too blind to see where and how this happens in your code. Could you help me and point me to your core d3.js code? 

Thank you very much, @beefoo !

**Comment by beefoo** [comment]
@trenkert Apologies, the codebase is a bit messy and I haven't touched it in a while!

If you are just interested in the visualization part that simply reads a json file and displays it in the transit format, you can look at the source of the homepage: [view-source:http://memoryunderground.com/](view-source:http://memoryunderground.com/)

This page reads a [static json file](http://memoryunderground.com/data/brian.json) and displays it like you see on [the homepage](http://memoryunderground.com/).  On the bottom of the source file, you can see all the files that are included to run the viz.  Primarily these are the key files:

```
...
<!-- misc vendor files -->
<script type="text/javascript" src="assets/js/vendor/jquery-1.11.1.min.js"></script>
<script type="text/javascript" src="assets/js/vendor/underscore-min.js"></script>
<script type="text/javascript" src="assets/js/vendor/backbone-min.js"></script>
<script type="text/javascript" src="assets/js/vendor/d3.min.js"></script>
 
<!-- misc config/utility files -->
<script type="text/javascript" src="assets/js/config.js"></script>
<script type="text/javascript" src="assets/js/helpers.js"></script>
<script type="text/javascript" src="assets/js/app.js"></script>

<!-- only needed for dragging/zooming -->
<script type="text/javascript" src="assets/js/vendor/jquery-ui.min.js"></script>
<script type="text/javascript" src="assets/js/vendor/jquery.ui.touch-punch.min.js"></script>
<script type="text/javascript" src="assets/js/vendor/jquery.panzoom.min.js"></script>

<!-- the main files needed for running the visualization -->
<script type="text/javascript" src="assets/js/models/transit.js"></script>
<script type="text/javascript" src="assets/js/collections/transits.js"></script>
<script type="text/javascript" src="assets/js/views/transit.show.js"></script>
``` 

You likely don't need all these files-- mostly just d3.js and the last three files are the "guts" of the visualization.  Backbone is mostly used to organize the code.  The best place to start would be [assets/js/views/transit.show.js](http://memoryunderground.com/assets/js/views/transit.show.js) which contains all the logic for displaying the visualization.
 
Hope that helps, and sorry again for the messiness!

Brian
