### ISSUE TITLE
How would one go about running the code in the repository. 

### ISSUE THREAD

**Issue by wolfiex** [beefoo/memory-underground#2]
I was wondering what the main html file required to run this would be. Alternatively is it possible to isolate the drawing algorithm from the php generated files.

**Comment by beefoo** [comment]
Yes, the drawing algorithm is entirely done on the client-side in javascript, and the PHP back-end is pretty much unnecessary (I've actually removed it from the website, but forgot to update this repository.) You can find most of the logic in this file:
https://github.com/beefoo/memory-underground/blob/master/assets/js/views/transit.show.js

But you can trace the logic by basically viewing the source directly on the website.  It basically uses SVG paths to generate the lines, so you can do that in any language.  Hope that helps!

**Comment by beefoo** [comment]
I've updated the repository and removed all the unnecessary PHP stuff, so hopefully it should be easier to follow now

**Comment by wolfiex** [comment]
Thanks a lot for that response, it's much easier to follow now! 

My last question would be in using it, which would you prefer to be referenced, the GitHub repository or the memoryunderground page (Or I guess ideally both)?

**Comment by beefoo** [comment]
Great!  The http://memoryunderground.com/ page would work, thanks
