### ISSUE TITLE
Question about the code 

### ISSUE THREAD

**Issue by shinji7800** [beefoo/memory-underground#4]
Hello,

Great works and thanks to sharing it ! 

I am not a developer, so my question is maybe strange ...

From what I understand this for node.js architecture. 
I don’t have node js on my server and can’t install it my provider don’t allow this.

Do you think it is possible that I adapt your code for js only ? 

Thanks 

Best regards

**Comment by beefoo** [comment]
Hi, you don't need node.js to use this code/app.  I only provide a node server for convenience for running the app locally.  You simply need to copy all the files to your providers hosting directory and it should work!

**Comment by shinji7800** [comment]
Hi,

sorry for this question I am not familiar with node.js (just know it is javascript server side...)

 thanks a lot !
